# Generated by Django 3.2.20 on 2023-08-14 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0002_alter_user_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=254, unique=True),
        ),
    ]
