# Generated by Django 3.2.20 on 2023-08-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=254, null=True, unique=True),
        ),
    ]
